name: Deploy

on:
  schedule:
    # run daily at 1:00 UTC format: minute hour day month weekday
    - cron:  '* 1 * * *'
  push:
    branches:
    - master
  workflow_dispatch:
jobs:
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-node@v1
      with:
        node-version: "14.x"

    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-
        
    - name: NPM Install
      run: npm install

    - name: Build Svelte
      env: 
        GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run build
    
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        cname: robinfrugte.dev
